#!/usr/bin/env python3


"""
Extracts candidate captions from the pdf2txt outputs.
"""


import sys
import util


# The logic below is new, TODO test it on the data


for block in util.blocks(sys.stdin):
    block = [line.strip() for line in block]
    # Identify potential captions:
    if len(block) == 1:
        # A single line, try to split it around colon-space
        try:
            part1, part2 = block[0].split(': ')
        except ValueError:
            continue
    elif len(block) == 2:
        # Two lines
        if ': ' in block[0] or ': ' in block[1]:
            # The colon is somewhere in the middle of one line, join them,
            # then treat like a single line
            line = ' '.join(block)
            try:
                part1, part2 = line.split(': ')
            except ValueError:
                continue
        elif block[0].endswith(':'):
            # The colon is at the end of the first line (does this ever
            # happen?)
            part1 = block[0][:-1]
            part2 = block[1]
        else:
            # The two parts are separated by a line break, but no colon
            part1, part2 = block
    else:
        continue
    # Cleanup:
    part1 = part1.strip()
    part2 = part2.strip()
    # Print:
    print('{}\t{}'.format(part1, part2))
