#!/usr/bin/env python3


"""
Extracts candidate captions from the pdf2txt outputs.
"""


import sys
import util


for block in util.blocks(sys.stdin):
    # Identify potential captions:
    if len(block) == 1:
        try:
            part1, part2 = block[0].split(': ')
        except ValueError:
            continue
    elif len(block) == 2:
        part1, part2 = block
    else:
        continue
    # Cleanup:
    part1 = part1.strip()
    part2 = part2.strip()
    # Print:
    print('{}\t{}'.format(part1, part2))
