#!/usr/bin/env python3


"""
Filters out bad candidate captions using various heuristics.
"""


import sys
import util


def seems_to_be_spaced(string):
    return string[1] == ' ' and string[3] == ' '


for line in sys.stdin:
    line = line.rstrip()
    part1, part2 = line.split('\t')
    # Various heuristics to filter out bad data:
    if not part1:
        continue
    if not part2:
        continue
    if ':' in part1:
        continue
    if ':' in part2:
        continue
    if not part1[0].isupper():
        continue
    if not part2[0].isupper():
        continue
    if not part1[-1].islower():
        continue
    if len(part1) > 1 and part1[1] == ' ':
        continue
    if part1.startswith('Quelle'):
        continue
    if part1.replace(' ', '').startswith('DasGesprächführte'):
        continue
    if part1.replace(' ', '').startswith('AndieserStelle'):
        continue
    if part1.endswith(' das'):
        continue
    if part1.endswith(' der'):
        continue
    if part1.endswith(' dem'):
        continue
    if part1.endswith(' den'):
        continue
    if part1.endswith(' des'):
        continue
    if part1.endswith(' die'):
        continue
    if part2.endswith('Mark') or part2.endswith('Mark.'):
        continue
    if part2.endswith('Euro') or part2.endswith('Euro.'):
        continue
    if 'SPIEGELONLINE' in part2.replace(' ', ''):
        continue
    if ' ' not in part1 or ' ' not in part2:
        continue
    # Print:
    print('{}\t{}'.format(part1, part2))

