#!/usr/bin/env python3


"""
Filters out bad candidate captions using various heuristics.
"""


import sys
import util


def seems_to_be_spaced(string):
    return string[1] == ' ' and string[3] == ' '


for line in sys.stdin:
    line = line.rstrip()
    part1, part2 = line.split('\t')
    # Various heuristics to filter out bad data:
    if not part1:
        continue
    if not part2:
        continue
    if not part1[0].isupper():
        continue
    if not part2[0].isupper():
        continue
    if not part1[-1].islower():
        continue
    if part1.startswith('Quelle'):
        continue
    if part1.startswith('Das Gespräch führte'):
        continue
    if part2.endswith('Mark') or part2.endswith('Mark.'):
        continue
    if part2.endswith('Euro') or part2.endswith('Euro.'):
        continue
    if ' ' not in part1 or ' ' not in part2:
        continue
    # Print:
    print('{}\t{}'.format(part1, part2))

