#!/usr/bin/env python

import config
import os
import random
import tweepy

auth = tweepy.OAuthHandler(config.consumer_key, config.consumer_secret)
auth.set_access_token(config.access_token, config.access_token_secret)
api = tweepy.API(auth)

bot_home = os.path.dirname(__file__)

while True:
    with open(os.path.join(bot_home, 'part1.txt')) as f:
        lines = list(f)
    part1 = random.choice(lines).strip()
    with open(os.path.join(bot_home, 'part2.txt')) as f:
        lines = list(f)
    part2 = random.choice(lines).strip()
    text = '{}: {}'.format(part1, part2)
    if len(text) <= 140:
       api.update_status(text)
       break
