#!/usr/bin/env python


import config
import os
import random
import tweepy


auth = tweepy.OAuthHandler(config.consumer_key, config.consumer_secret)
auth.set_access_token(config.access_token, config.access_token_secret)
api = tweepy.API(auth)

bot_home = os.path.dirname(__file__)
parts1 = []
parts2 = []

with open(os.path.join(bot_home, 'captions.txt')) as f:
    for line in f:
        line = line.rstrip()
        part1, part2 = line.split('\t')
        parts1.append(part1)
        parts2.append(part2)

while True:
    part1 = random.choice(parts1)
    part2 = random.choice(parts2)
    text = '{}: {}'.format(part1, part2)
    if len(text) <= 140:
       api.update_status(text)
       break
