#!/usr/bin/env python

import config
import random
import tweepy

auth = tweepy.OAuthHandler(config.consumer_key, config.consumer_secret)
auth.set_access_token(config.access_token, config.access_token_secret)
api = tweepy.API(auth)

while True:
    with open('part1.txt') as f:
        lines = list(f)
    part1 = random.choice(lines).strip()
    with open('part2.txt') as f:
        lines = list(f)
    part2 = random.choice(lines).strip()
    text = '{}: {}'.format(part1, part2)
    if len(text) <= 140:
       api.update_status(text)
       break
